// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASVPFPhP620IH2d9gqASO1ARnd-ojasyM',
    appId: '1:808354795720:web:39675777871732df9f55fd',
    messagingSenderId: '808354795720',
    projectId: 'todo-app-18579',
    authDomain: 'todo-app-18579.firebaseapp.com',
    storageBucket: 'todo-app-18579.appspot.com',
    measurementId: 'G-72P176W9SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjli10xn-Neo0543Z7e3jIduyEsKQo7r4',
    appId: '1:808354795720:android:8d5b976dad157a5d9f55fd',
    messagingSenderId: '808354795720',
    projectId: 'todo-app-18579',
    storageBucket: 'todo-app-18579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9fpFLNtPku-upvOm0Ysoj-Q0N38A8QGE',
    appId: '1:808354795720:ios:b123a84a7871a0cf9f55fd',
    messagingSenderId: '808354795720',
    projectId: 'todo-app-18579',
    storageBucket: 'todo-app-18579.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9fpFLNtPku-upvOm0Ysoj-Q0N38A8QGE',
    appId: '1:808354795720:ios:b123a84a7871a0cf9f55fd',
    messagingSenderId: '808354795720',
    projectId: 'todo-app-18579',
    storageBucket: 'todo-app-18579.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASVPFPhP620IH2d9gqASO1ARnd-ojasyM',
    appId: '1:808354795720:web:072a7132043cc9279f55fd',
    messagingSenderId: '808354795720',
    projectId: 'todo-app-18579',
    authDomain: 'todo-app-18579.firebaseapp.com',
    storageBucket: 'todo-app-18579.appspot.com',
    measurementId: 'G-YB3SMR7V3Q',
  );
}
